### ISSUE TITLE
Create a public binder demo of the acquisition notebook

### ISSUE THREAD

**Issue by bergmanngabor** [IncQueryLabs/incquery-server-jupyter#17]
It is OK if the demo only works with non-public credentials (and non-public IQS server).

However, as the notebook requires the generated Python client library for the Connector API, this separate sdist library must be: 
- generated & packaged
- put on the public IQS instance
- installed in the binder environment setup scripts

**Comment by abelhegedus** [comment]
As discussed @pappist will take care of the new package after the 2020.2 release.

**Comment by abelhegedus** [comment]
Acquisition API has moved to the main API and PyPI packages are now available, will be available in Binder after #41 while example notebook already exists ( https://github.com/IncQueryLabs/incquery-server-jupyter/blob/master/example-notebook-home/acquisition-test.ipynb ), so closing this.
