### ISSUE TITLE
Refer to folder containing the public IQS API Python client library

### ISSUE THREAD

**Issue by benedekh** [IncQueryLabs/incquery-server-jupyter#24]
In the README.md a fixed version of the IQS API Python client library is referred. Since the text context says we should download the library from public IQS demo server, it might be better to just refer to the [folder](https://openmbee.incquery.io/client/) containing the different versions of the library, instead of directly referring to a [version](https://openmbee.incquery.io/client/incqueryserver-api-python-client-0.11.0.tar.gz).

What do you think @bergmanngabor ?

**Comment by bergmanngabor** [comment]
I agree. Will be fixed with the documentation rewrite, see https://github.com/IncQueryLabs/incquery-server-jupyter/pull/31
