### ISSUE TITLE
Publish Conda packages

### ISSUE THREAD

**Issue by bergmanngabor** [IncQueryLabs/incquery-server-jupyter#29]
See e.g. ways to have them built on conda-forge.

See steps outlined here: https://github.com/IncQueryLabs/incquery-server-jupyter/issues/1#issuecomment-640207621

**Comment by mintingchen** [comment]
Thanks for the comment on https://github.com/IncQueryLabs/incquery-server-jupyter/issues/40#issuecomment-775965003. But conda-forge is best handled on the vendor side. So resolving https://github.com/IncQueryLabs/incquery-server-jupyter/issues/29 is a priority for us.

**Comment by abelhegedus** [comment]
We will deal with this in the near future.

**Comment by FuzesiMate** [comment]
## Steps to produce a conda package from PyPI:
* Read the documentation: https://conda-forge.org/docs/maintainer/adding_pkgs.html
* Activate a conda environment (preferably a new, clean one)
* Install Grayskull by `conda install grayskull`
* Install conda build by `conda install conda-build`
* Generate `meta.yaml` files: 
    * `grayskull pypi incqueryserver-api-python-client` and ` grayskull pypi incqueryserver-jupyter`
    * Check the generated `meta.yaml` files and fill the `about` and `license` parts properly (see previous versions)
* Go to the folder where `meta.yaml` is present and run `conda build . -c conda-forge` for both packages
* Run `conda install --use-local <conda_package_location>/conda-bld/noarch/incqueryserver-api-python-client-<version>-py.tar.bz2`
* Run `conda install --use-local <conda_package_location>/conda-bld/noarch/incqueryserver-jupyter-<version>-py.tar.bz2`
* Try your local install (make sure that you use the packages from this conda environment, and not from the system root).

**Comment by FuzesiMate** [comment]
Pull request in conda-forge: https://github.com/conda-forge/staged-recipes/pull/13994

**Comment by abelhegedus** [comment]
@mintingchen note that 0.17.1 version of the Python packages are now available on conda-forge: https://anaconda.org/conda-forge/incqueryserver-jupyter and https://anaconda.org/conda-forge/incqueryserver-api-python-client
