### ISSUE TITLE
Publishing the IQS packages to Conda-Forge

### ISSUE THREAD

**Issue by mintingchen** [IncQueryLabs/incquery-server-jupyter#40]
Hi, I am using the IQS client package on a project, and I would like to publish my package to Conda which requires the IQS package to be available on Conda as well. It will be great to have the Conda version soon. Thanks!

**Comment by abelhegedus** [comment]
We have looked into Conda previously, you can find the relevant comment here: https://github.com/IncQueryLabs/incquery-server-jupyter/issues/1#issuecomment-640207621 and the tracking issue here: https://github.com/IncQueryLabs/incquery-server-jupyter/issues/29

Note that based on the existing descriptors and the [PyPI packages](https://github.com/IncQueryLabs/incquery-server-jupyter#pypi-packages), I guess anybody would be able to initialize the conda-forge versions.

**Comment by abelhegedus** [comment]
Duplicate: #29
