### ISSUE TITLE
Customize display of ValidationResults

### ISSUE THREAD

**Issue by bergmanngabor** [IncQueryLabs/incquery-server-jupyter#5]

**Comment by bergmanngabor** [comment]
c.f https://plot.ly/pandas/pie-charts/

**Comment by bergmanngabor** [comment]
Current status:
- Only the generic compartment-based validation API is supported, not the TWC-specific API
- The names of violating elements are not visible due to upstream bug https://github.com/IncQueryLabs/incquery-server/issues/1195 (has been fixed since)

**Comment by bergmanngabor** [comment]
The latter problem is now fixed in c2893da. Do we care about the former?

**Comment by abelhegedus** [comment]
> The latter problem is now fixed in c2893da. Do we care about the former?

No, not for now.
