### ISSUE TITLE
Set up a public demo

### ISSUE THREAD

**Issue by bergmanngabor** [IncQueryLabs/incquery-server-jupyter#7]

**Comment by bergmanngabor** [comment]
The public demo works in MyBinder, albeit a bit slow and unstable. 

Microsoft's Azure Notebooks is a possible alternative free hosted service that is worth looking into. Self-hosting a public-facing JupyterHub for the demo would be another option.

**Comment by bergmanngabor** [comment]
Next step: provide a public demo notebook that showcases those features only that are executable by the public demo user on the public demo IQS instance.

**Comment by istvanrath** [comment]
Please adjust notebook so that `"mms-index:/orgs/9ff6af30-af8a-4f9d-a26b-499010ba5b6e/projects/PROJECT-0e791c0e-16fe-422f-8f85-462ab035ce99/refs/master/commits/8598d33b-4950-4355-a404-18b0d8148b47"` is used for validation.

**Comment by bergmanngabor** [comment]
> Please adjust notebook so that `"mms-index:/orgs/9ff6af30-af8a-4f9d-a26b-499010ba5b6e/projects/PROJECT-0e791c0e-16fe-422f-8f85-462ab035ce99/refs/master/commits/8598d33b-4950-4355-a404-18b0d8148b47"` is used for validation.

Done in commit 95eed2daf307a80bd7eee453522fec9cf8a2edf5

**Comment by istvanrath** [comment]
Example VQL you can use for coverage analysis:

```
pattern requirement(class : Class){
	find sysml.Requirement(class,_);
}

pattern refined(r1,r2) {
	find sysml.Requirement_RefinedBy+(r1,r2);
}

pattern requCoveredByDirect(originalRequ:Class, something) {
	find sysml.Requirement_SatisfiedBy(originalRequ,something);
} or {
	find sysml.Requirement_VerifiedBy(originalRequ,something);
}

pattern requCoveredBy(originalRequ:Class, something) {
	find requCoveredByDirect(originalRequ,something);
} or {
	find refined(originalRequ,refinedRequ);
	find requCoveredByDirect(refinedRequ,something);
}
```

**Comment by bergmanngabor** [comment]
What's wrong with the currently used coverage query?

**Comment by bergmanngabor** [comment]
The public demo went live.
